version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - PORT=${PORT:-5000}
      - NODE_NAME=${NODE_NAME}
      - NODE_ADDRESS=${NODE_ADDRESS}
      - NODE_PORT=${NODE_PORT}
      - NODE_USER=${NODE_USER}
      - NODE_PASSWORD=${NODE_PASSWORD}
      - NODE_TLS=${NODE_TLS}
      - NODE_PLUGIN=${NODE_PLUGIN}
      - NODE_TCP_FAST_OPEN=${NODE_TCP_FAST_OPEN} 